=== Sydpy/NumerisationMaquette/schemas/maquette.xsd
<?xml version="1.0" encoding="Utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://raw.githubusercontent.com/Sydpy/NumerisationMaquette/master/schemas">

  <xs:element name="Maquette">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Semestre">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:minInclusive value="1"/>
              <xs:maxInclusive value="10"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <!-- FAUT QUE CE SOIT UNE REF VERS PROMO -->
        <xs:element name="Promo" type="Promo" />
        <xs:element name="NbUFAChoisir" type="xs:int" default="0"/>
        <xs:element name="UFs">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="UF" type="UF" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
          <xs:key name="UFCode">
            <xs:selector xpath="./UF"/>
            <xs:field xpath="@code"/>
          </xs:key>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="UF">
    <xs:sequence>
      <xs:element name="Intitulé" type="xs:string"/>
      <xs:element name="Hétérogène" type="xs:boolean"/>
      <xs:element name="ECTS" type="xs:float"/>
      <xs:element name="ParCompétences" type="xs:boolean"/>
      <!-- FAUT QUE CE SOIT UNE REF VERS GRANDDOMAINE-->
      <xs:element name="GdDomaine" type="xs:ID" minOccurs="0" />
      <xs:element name="Responsable" type="xs:ID"/>

      <xs:element name="UEs">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="UE" type="UE" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="code" type="xs:ID"/>
  </xs:complexType>

  <xs:complexType name="UFObligatoire">
    <xs:complexContent>
      <xs:extension base="UF">
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="UFChoix">
    <xs:complexContent>
      <xs:extension base="UF">
        <xs:sequence>
          <xs:element name="Spécialité" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="UE">
    <xs:sequence>
      <xs:element name="Intitulé" type="xs:string"/>
      <xs:element name="Coefficient" type="xs:float"/>
      <xs:element name="ParCompétences" type="xs:boolean"/>
      <!-- FAUT QUE CE SOIT UNE REF VERS PERSONNEL-->
      <xs:element name="Responsable" type="xs:ID"/>
      <xs:element name="HeuresCM" type="xs:float"/>
      <xs:element name="HeuresTD" type="xs:float"/>
      <xs:element name="HeuresTP" type="xs:float"/>

      <xs:element name="Compétences">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Compétence" type="Compétence" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name="Épreuves">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Épreuve" type="Épreuve" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

    </xs:sequence>
    <xs:attribute name="Code" type="xs:ID"/>
  </xs:complexType>

  <xs:complexType name="Compétence">
    <xs:sequence>
      <xs:element name="Intitulé" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Épreuve">
    <xs:sequence>
      <xs:element name="Intitulé" type="xs:string"/>
      <xs:element name="Coefficient" type="xs:float"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== Sydpy/NumerisationMaquette/xml/maquettes/maquette_4AE_SE_S2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Maquette xmlns="http://mdsi.etudinsa.org/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="../schemas/maquette.xsd">

    <Semestre>2</Semestre>
    <Promo>PROMO-4AE-SE</Promo>
    <NbUFAChoisir>0</NbUFAChoisir>
    <UFs>
        <UFObligatoire code="I4AEIL11">
            <Intitulé>Informatique logicielle et réseaux</Intitulé>
            <Hétérogène>true</Hétérogène>
            <ECTS>5</ECTS>
            <ParCompétences>false</ParCompétences>
            <Responsable>monteil</Responsable>
            <UEs>
                <UE>
                    <Intitulé>Interconnexion de réseaux</Intitulé>
                    <Coefficient>0.333</Coefficient>
                    <ParCompétences>false</ParCompétences>
                    <Responsable>chassot</Responsable>
                    <HeuresCM>15</HeuresCM>
                    <HeuresTD>1.25</HeuresTD>
                    <HeuresTP>8.25</HeuresTP>
                    <Épreuves>
                        <Épreuve code="E1">
                            <Intitulé>Contrôle</Intitulé>
                            <Coefficient>1</Coefficient>
                        </Épreuve>
                    </Épreuves>
                </UE>
                <UE>
                    <Intitulé>Temps réel</Intitulé>
                    <Coefficient>0.333</Coefficient>
                    <ParCompétences>false</ParCompétences>
                    <Responsable>hladik</Responsable>
                    <HeuresCM>8.75</HeuresCM>
                    <HeuresTD>2.50</HeuresTD>
                    <HeuresTP>13.75</HeuresTP>
                    <Épreuves>
                        <Épreuve code="E2">
                            <Intitulé>Projet</Intitulé>
                            <Coefficient>1</Coefficient>
                        </Épreuve>
                    </Épreuves>
                </UE>
                <UE>
                    <Intitulé>Programmation Orientée Objet</Intitulé>
                    <Coefficient>0.333</Coefficient>
                    <ParCompétences>false</ParCompétences>
                    <Responsable>monteil</Responsable>
                    <HeuresCM>8.75</HeuresCM>
                    <HeuresTD>6.25</HeuresTD>
                    <HeuresTP>24.75</HeuresTP>
                    <Épreuves>
                        <Épreuve code="E3">
                            <Intitulé>BE+QCM</Intitulé>
                            <Coefficient>1</Coefficient>
                        </Épreuve>
                    </Épreuves>
                </UE>
            </UEs>
        </UFObligatoire>
        <UFObligatoire code="I4AESE51">
            <Intitulé>Gestion de l'énergie pour systèmes embarqués</Intitulé>
            <Hétérogène>false</Hétérogène>
            <ECTS>5</ECTS>
            <ParCompétences>false</ParCompétences>
            <Responsable>tounsi</Responsable>
            <UEs>
                <UE>
                    <Intitulé>Sources d'énergie pour systèmes embarqués</Intitulé>
                    <Coefficient>0.333</Coefficient>
                    <ParCompétences>false</ParCompétences>
                    <Responsable>dilhac</Responsable>
                    <HeuresCM>7.50</HeuresCM>
                    <HeuresTD>1.25</HeuresTD>
                    <HeuresTP>2.75</HeuresTP>
                    <Épreuves>
                        <Épreuve code="E1">
                            <Intitulé>Contrôle</Intitulé>
                            <Coefficient>1</Coefficient>
                        </Épreuve>
                    </Épreuves>
                </UE>
                <UE>
                    <Intitulé>Convertisseurs de puissance</Intitulé>
                    <Coefficient>0.666</Coefficient>
                    <ParCompétences>false</ParCompétences>
                    <Responsable>tounsi</Responsable>
                    <HeuresCM>11.25</HeuresCM>
                    <HeuresTD>6.25</HeuresTD>
                    <HeuresTP>11</HeuresTP>
                    <Épreuves>
                        <Épreuve code="E2">
                            <Intitulé>Projet</Intitulé>
                            <Coefficient>1</Coefficient>
                        </Épreuve>
                    </Épreuves>
                </UE>
            </UEs>
        </UFObligatoire>
        <UFObligatoire code="I4AESY21">
            <Intitulé>Optimisation des systèmes discrets et continus</Intitulé>
            <Hétérogène>false</Hétérogène>
            <ECTS>5</ECTS>
            <ParCompétences>false</ParCompétences>
            <Responsable>lelann</Responsable>
            <UEs>
                <UE>
                    <Intitulé>Graphes</Intitulé>
                    <Coefficient>0.35</Coefficient>
                    <ParCompétences>false</ParCompétences>
                    <Responsable>chantery</Responsable>
                    <HeuresCM>13.75</HeuresCM>
                    <HeuresTD>12.50</HeuresTD>
                    <HeuresTP>0</HeuresTP>
                    <Épreuves>
                        <Épreuve code="E1">
                            <Intitulé>Contrôle</Intitulé>
                            <Coefficient>1</Coefficient>
                        </Épreuve>
                    </Épreuves>
                </UE>
                <UE>
                    <Intitulé>Processus Stochastiques - Réseaux de Petri</Intitulé>
                    <Coefficient>0.35</Coefficient>
                    <ParCompétences>false</ParCompétences>
                    <Responsable>subias</Responsable>
                    <HeuresCM>15</HeuresCM>
                    <HeuresTD>7.50</HeuresTD>
                    <HeuresTP>0</HeuresTP>
                    <Épreuves>
                        <Épreuve code="E2">
                            <Intitulé>Contrôle</Intitulé>
                            <Coefficient>1</Coefficient>
                        </Épreuve>
                    </Épreuves>
                </UE>
                <UE>
                    <Intitulé>Commande optimale</Intitulé>
                    <Coefficient>0.20</Coefficient>
                    <ParCompétences>false</ParCompétences>
                    <Responsable>lelann</Responsable>
                    <HeuresCM>11.25</HeuresCM>
                    <HeuresTD>8.75</HeuresTD>
                    <HeuresTP>0</HeuresTP>
                    <Épreuves>
                        <Épreuve code="E3">
                            <Intitulé>Contrôle</Intitulé>
                            <Coefficient>1</Coefficient>
                        </Épreuve>
                    </Épreuves>
                </UE>
            </UEs>
        </UFObligatoire>
        <UFObligatoire code="I4AEAU21">
            <Intitulé>Automatique appliquée</Intitulé>
            <Hétérogène>false</Hétérogène>
            <ECTS>5</ECTS>
            <ParCompétences>false</ParCompétences>
            <Responsable>lecorre</Responsable>
            <UEs>
                <UE>
                    <Intitulé>TP Automatique</Intitulé>
                    <Coefficient>0.5</Coefficient>
                    <ParCompétences>false</ParCompétences>
                    <Responsable>lecorre</Responsable>
                    <HeuresCM>2.50</HeuresCM>
                    <HeuresTD>0</HeuresTD>
                    <HeuresTP>16.50</HeuresTP>
                    <Épreuves>
                        <Épreuve code="E1">
                            <Intitulé>Contrôle</Intitulé>
                            <Coefficient>1</Coefficient>
                        </Épreuve>
                    </Épreuves>
                </UE>
                <UE>
                    <Intitulé>Mini projet Automatique</Intitulé>
                    <Coefficient>0.5</Coefficient>
                    <ParCompétences>false</ParCompétences>
                    <Responsable>mahout</Responsable>
                    <HeuresCM>0</HeuresCM>
                    <HeuresTD>0</HeuresTD>
                    <HeuresTP>16.50</HeuresTP>
                    <Épreuves>
                        <Épreuve code="E2">
                            <Intitulé>Contrôle</Intitulé>
                            <Coefficient>1</Coefficient>
                        </Épreuve>
                    </Épreuves>
                </UE>
            </UEs>
        </UFObligatoire>
        <UFObligatoire code="I4CCGA21">
            <Intitulé>Grandir en autonomie</Intitulé>
            <Hétérogène>true</Hétérogène>
            <ECTS>4</ECTS>
            <ParCompétences>false</ParCompétences>
            <Responsable>rossard</Responsable>
            <UEs>
                <UE>
                    <Intitulé>APS</Intitulé>
                    <Coefficient>0.5</Coefficient>
                    <ParCompétences>false</ParCompétences>
                    <Responsable>rossard</Responsable>
                    <HeuresCM>0</HeuresCM>
                    <HeuresTD>25</HeuresTD>
                    <HeuresTP>0</HeuresTP>
                    <Épreuves>
                        <Épreuve code="E1">
                            <Intitulé>Contrôle</Intitulé>
                            <Coefficient>1</Coefficient>
                        </Épreuve>
                    </Épreuves>
                </UE>
                <UE>
                    <Intitulé>PPI</Intitulé>
                    <Coefficient>0.5</Coefficient>
                    <ParCompétences>false</ParCompétences>
                    <Responsable>dupont</Responsable>
                    <HeuresCM>0</HeuresCM>
                    <HeuresTD>0</HeuresTD>
                    <HeuresTP>0</HeuresTP>
                    <Épreuves>
                        <Épreuve code="E2">
                            <Intitulé>Contrôle</Intitulé>
                            <Coefficient>1</Coefficient>
                        </Épreuve>
                    </Épreuves>
                </UE>
                <UE>
                    <Intitulé>Module d'ouverture (semaine CREDIGE)</Intitulé>
