=== Sydpy/NumerisationMaquette/schemas/personnels.xsd
<?xml version="1.0" encoding="Utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://raw.githubusercontent.com/Sydpy/NumerisationMaquette/master/schemas">
  
  <xs:element name="Personnels">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Personnel" type="Personnel" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Personnel">
    <xs:sequence>
      <xs:element name="Nom" type="xs:string"/>
      <xs:element name="Prénom" type="xs:string"/>
      <xs:element name="Grade" type="xs:string"/>
      <xs:element name="Bureau" type="xs:string"/>
      <xs:element name="Mail" type="xs:string"/>
      <xs:element name="Téléphone" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:ID"/>
  </xs:complexType>

</xs:schema>

=== Sydpy/NumerisationMaquette/xml/personnels.xml
<?xml version="1.0" encoding="UTF-8"?>

<Personnels xmlns="personnels"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="personnels ../schemas/personnels.xsd">

    <Personnel id="guermouc">
        <Nom>Guermouche</Nom>
        <Prénom>Nawal</Prénom>
        <Grade>Maître de conférences</Grade>
        <Bureau>Table</Bureau>
        <Mail>guermouc@insa-toulouse.fr</Mail>
        <Téléphone>+33615458745</Téléphone>
    </Personnel>


    <Personnel id="vernadat">
        <Nom>Vernadat</Nom>
        <Prénom>François</Prénom>
        <Grade>Maître de conférences</Grade>
        <Bureau>Table</Bureau>
        <Mail>vernadat@insa-toulouse.fr</Mail>
        <Téléphone>+33615458785</Téléphone>
    </Personnel>


    <Personnel id="jcarrey">
        <Nom>Carrey</Nom>
        <Prénom>Julian</Prénom>
        <Grade>Maître de conférences</Grade>
        <Bureau>Table</Bureau>
        <Mail>jcarrery@insa-toulouse.fr</Mail>
        <Téléphone>+33619858785</Téléphone>
    </Personnel>


    <Personnel id="lebotlan">
        <Nom>Lebotlan</Nom>
        <Prénom>Didier</Prénom>
        <Grade>Maître de conférences</Grade>
        <Bureau>Table</Bureau>
        <Mail>lebotlan@insa-toulouse.fr</Mail>
        <Téléphone>+33749358785</Téléphone>
    </Personnel>


    <Personnel id="boyer">
        <Nom>Boyer</Nom>
        <Prénom>Alain</Prénom>
        <Grade>Maître de conférences</Grade>
        <Bureau>Table</Bureau>
        <Mail>alain.boyer@insa-toulouse.fr</Mail>
        <Téléphone>+33619348785</Téléphone>
    </Personnel>


    <Personnel id="rossard">
        <Nom>Rossard</Nom>
        <Prénom>Sylvie</Prénom>
        <Grade>Maître de conférences</Grade>
        <Bureau>Table</Bureau>
        <Mail>sylvie.rossard@insa-toulouse.fr</Mail>
        <Téléphone>+33619858095</Téléphone>
    </Personnel>


    <Personnel id="grusea">
        <Nom>Grusea</Nom>
        <Prénom>Simona</Prénom>
        <Grade>Maître de conférences</Grade>
        <Bureau>Table</Bureau>
        <Mail>simona.grusea@insa-toulouse.fr</Mail>
        <Téléphone>+33619836785</Téléphone>
    </Personnel>

    <Personnel id="dragomirescu">
        <Nom>Dragomirescu</Nom>
        <Prénom>Daniela</Prénom>
        <Grade>Directeur</Grade>
        <Bureau>Table</Bureau>
        <Mail>daniela.dragomirescu@insa-toulouse.fr</Mail>
        <Téléphone>+0561336379</Téléphone>
    </Personnel>

    <Personnel id="dauxois">
        <Nom>Dauxois</Nom>
        <Prénom>Jean-Yves</Prénom>
        <Grade>Directeur</Grade>
        <Bureau>1</Bureau>
        <Mail>jean-yves.dauxois@insa-toulouse.fr</Mail>
        <Téléphone>+0561559315</Téléphone>
    </Personnel>

    <Personnel id="pic">
        <Nom>Pic</Nom>
        <Prénom>Jean-Stéphane</Prénom>
        <Grade>Directeur</Grade>
        <Bureau>table</Bureau>
        <Mail>jean-stephane.pic@insa-toulouse.fr</Mail>
        <Téléphone>+0561559747</Téléphone>
    </Personnel>

    <Personnel id="schimtz">
        <Nom>Schmitz</Nom>
        <Prénom>Philippe</Prénom>
        <Grade>Directeur</Grade>
        <Bureau>table</Bureau>
        <Mail>philippe.schmitz@insa-toulouse.fr</Mail>
        <Téléphone>+0561559513</Téléphone>
    </Personnel>

    <Personnel id="duprat">
        <Nom>Duprat</Nom>
        <Prénom>Frédéric</Prénom>
        <Grade>Directeur</Grade>
        <Bureau>table</Bureau>
        <Mail>frederic.duprat@insa-toulouse.fr</Mail>
        <Téléphone>+0561559513</Téléphone>
    </Personnel>

    <Personnel id="paredes">
        <Nom>Paredes</Nom>
        <Prénom>Manuel</Prénom>
        <Grade>Directeur</Grade>
        <Bureau>table</Bureau>
        <Mail>manuel.paredes@insa-toulouse.fr</Mail>
        <Téléphone>+0561559513</Téléphone>
    </Personnel>

    <Personnel id="vignolles">
        <Nom>Vignolles</Nom>
        <Prénom>David</Prénom>
        <Grade>Directeur</Grade>
        <Bureau>table</Bureau>
        <Mail>david.vignolles@insa-toulouse.fr</Mail>
        <Téléphone>+0561559513</Téléphone>
    </Personnel>

    <Personnel id="hebrard">
        <Nom>Hébrard</Nom>
        <Prénom>Gilles</Prénom>
        <Grade>Directeur</Grade>
        <Bureau>table</Bureau>
        <Mail>gilles.hebrard@insa-toulouse.fr</Mail>
        <Téléphone>+0561559513</Téléphone>
    </Personnel>



</Personnels>
