=== Sydpy/NumerisationMaquette/schemas/promos.xsd
<?xml version="1.0" encoding="Utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Promos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Promo" type="Promo" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Promo">
    <xs:sequence>
      <xs:element name="Année" type="xs:int"/>
      <!-- FAUT QUE CE SOIT UNE REF VERS DEPARTEMENT-->
      <xs:element name="Département" type="Departement"/>
      <xs:element name="Maquettes">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Maquette" type="Maquette" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType> 
      </xs:element>
    </xs:sequence>
    <xs:attribute name="ID" type="xs:ID"/>
  </xs:complexType>

  <xs:complexType name="PromoPreOrientation">
    <xs:complexContent>
      <xs:extension base="Promo">
        <xs:element name="PréOrientation" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="PromoOrientation">
    <xs:complexContent>
      <xs:extension base="Promo">
        <xs:element name="Orientation" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="PromoOrientationSpe">
    <xs:complexContent>
      <xs:extension base="PromoOrientation">
        <xs:element name="Spécialité" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>



</xs:schema>

=== Sydpy/NumerisationMaquette/xml/promos.xml
<?xml version="1.0" encoding="UTF-8"?>

<Promos xmlns="promos"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="promos ../schemas/promos.xsd">

  <Promo id="PROMO-1A">
    <Année>1</Année>
    <Département>STPI</Département>
  </Promo>

  <Promo id="PROMO-2MIC">
    <Année>2</Année>
    <Département>STPI</Département>
    <PréOrientation>Modélisation, Informatique et Communication</PréOrientation>
  </Promo>

  <Promo id="PROMO-2IC">
    <Année>2</Année>
    <Département>STPI</Département>
    <PréOrientation>Ingénierie de la Construction</PréOrientation>
  </Promo>

  <Promo id="PROMO-2IMACS">
    <Année>2</Année>
    <Département>STPI</Département>
    <PréOrientation>Ingénierie des Matériaux, Composants et Systèmes</PréOrientation>
  </Promo>

  <Promo id="PROMO-2ICBE">
    <Année>2</Année>
    <Département>STPI</Département>
    <PréOrientation>Ingénierie Chimique, Biochimique et Environnementale</PréOrientation>
  </Promo>

  <Promo id="PROMO-3MIC">
    <Année>3</Année>
    <Département>STPI</Département>
    <PréOrientation>Modélisation, Informatique et Communication</PréOrientation>
  </Promo>

  <Promo id="PROMO-3IC">
    <Année>3</Année>
    <Département>STPI</Département>
    <PréOrientation>Ingénierie de la Construction</PréOrientation>
  </Promo>

  <Promo id="PROMO-3IMACS">
    <Année>3</Année>
    <Département>STPI</Département>
    <PréOrientation>Ingénierie des Matériaux, Composants et Systèmes</PréOrientation>
  </Promo>

  <Promo id="PROMO-3ICBE">
    <Année>3</Année>
    <Département>STPI</Département>
    <PréOrientation>Ingénierie Chimique, Biochimique et Environnementale</PréOrientation>
  </Promo>

  <Promo id="PROMO-4IR">
    <Année>4</Année>
    <Département>GEI</Département>
    <Orientation>Informatique et Réseaux</Orientation>
  </Promo>

  <Promo id="PROMO-4MA">
    <Année>4</Année>
    <Département>GMM</Département>
    <Orientation>Mathématiques Appliquées</Orientation>
  </Promo>

  <Promo id="PROMO-4AE">
    <Année>4</Année>
    <Département>GEI</Département>
    <Orientation>Automatique et Electronique</Orientation>
  </Promo>

  <Promo id="PROMO-4GP">
    <Année>4</Année>
    <Département>GP</Département>
    <Orientation>Génie Physique</Orientation>
  </Promo>

  <Promo id="PROMO-4GPE">
    <Année>4</Année>
    <Département>GPE</Département>
    <Orientation>Génie des Procédés et Environnement</Orientation>
  </Promo>

  <Promo id="PROMO-4GB">
    <Année>4</Année>
    <Département>GB</Département>
    <Orientation>Génie Biologique</Orientation>
  </Promo>

  <Promo id="PROMO-4GC">
    <Année>4</Année>
    <Département>GC</Département>
    <Orientation>Génie Civil</Orientation>
  </Promo>

  <Promo id="PROMO-4GM">
    <Année>4</Année>
    <Département>GM</Département>
    <Orientation>Génie Mécanique</Orientation>
  </Promo>

  <Promo id="PROMO-5SDBD">
    <Année>5</Année>
    <Département>GEI</Département>
    <Orientation>
      Informatique et Réseaux
      <Spécialité>Systèmes Distribués et Big Data</Spécialité>
    </Orientation>
  </Promo>

  <Promo id="PROMO-5SIEC">
    <Année>5</Année>
    <Département>GEI</Département>
    <Orientation>
      Informatique et Réseaux
      Automatique et Electronique
      <Spécialité> Systèmes Informatiques Embarqués Critiques</Spécialité>
    </Orientation>
  </Promo>

</Promos>
